version: '3'
services:
  node1:
    build:
      context: ./btc_node_1
  node2:
    build:
      context: ./btc_node_2
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend